#goal definition
float32 acquisition_distance
float32 deposit_radius_tolerance
string output_path
---
#result definition
int32 percentage
string skillStatus
string outcome
local_perception_msgs/QualityArr output

---
#feedback
int32 percentage
string skillStatus
